/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ViewLayer;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author zerme
 */
public class frmMain extends javax.swing.JFrame {

    public static frmProductos fProductos;
    public static frmCategorias fCategorias;
    public static frmClientes fClientes;
    public static frmContactos fContactos;
    public static frmEstados fEstados;
    public static frmMunicipios fMunicipios;
    public static frmLocalidades fLocalidades;
    public static frmProveedores fProveedores;
    public static frmSucursales fSucursales;
    public static frmUsuarios fUsuarios;
    public static frmProductosProveedores fProuctosProvedores;
    
    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        ImageIcon icon = new ImageIcon(getClass().getResource("/Icons/Background.jpg"));
        Image image =icon.getImage();
        desktopPane = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){ g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        jMenuBar1 = new javax.swing.JMenuBar();
        mnArchivo = new javax.swing.JMenu();
        btnSalir = new javax.swing.JCheckBoxMenuItem();
        mnCatalogos = new javax.swing.JMenu();
        btnProductos = new javax.swing.JCheckBoxMenuItem();
        btnCategorias = new javax.swing.JCheckBoxMenuItem();
        btnClientes = new javax.swing.JCheckBoxMenuItem();
        btnContactos = new javax.swing.JCheckBoxMenuItem();
        btnLocalidades = new javax.swing.JCheckBoxMenuItem();
        btnMunicipios = new javax.swing.JCheckBoxMenuItem();
        btnEstados = new javax.swing.JCheckBoxMenuItem();
        btnUsuarios = new javax.swing.JCheckBoxMenuItem();
        btnSucursales = new javax.swing.JCheckBoxMenuItem();
        btnProveedores = new javax.swing.JCheckBoxMenuItem();
        btnProductosProveedores = new javax.swing.JCheckBoxMenuItem();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        mnArchivo.setText("Archivo");

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        mnArchivo.add(btnSalir);

        jMenuBar1.add(mnArchivo);

        mnCatalogos.setText("Catalogos");

        btnProductos.setText("Productos");
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });
        mnCatalogos.add(btnProductos);

        btnCategorias.setText("Categorias");
        btnCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoriasActionPerformed(evt);
            }
        });
        mnCatalogos.add(btnCategorias);

        btnClientes.setText("Clientes");
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        mnCatalogos.add(btnClientes);

        btnContactos.setText("Contactos");
        btnContactos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContactosActionPerformed(evt);
            }
        });
        mnCatalogos.add(btnContactos);

        btnLocalidades.setText("Localidades");
        btnLocalidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocalidadesActionPerformed(evt);
            }
        });
        mnCatalogos.add(btnLocalidades);

        btnMunicipios.setText("Municipios");
        btnMunicipios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMunicipiosActionPerformed(evt);
            }
        });
        mnCatalogos.add(btnMunicipios);

        btnEstados.setText("Estados");
        btnEstados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadosActionPerformed(evt);
            }
        });
        mnCatalogos.add(btnEstados);

        btnUsuarios.setText("Usuarios");
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        mnCatalogos.add(btnUsuarios);

        btnSucursales.setText("Sucursales");
        btnSucursales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSucursalesActionPerformed(evt);
            }
        });
        mnCatalogos.add(btnSucursales);

        btnProveedores.setText("Proveedores");
        btnProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedoresActionPerformed(evt);
            }
        });
        mnCatalogos.add(btnProveedores);

        btnProductosProveedores.setText("Productos-Proveedores");
        btnProductosProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosProveedoresActionPerformed(evt);
            }
        });
        mnCatalogos.add(btnProductosProveedores);

        jMenuBar1.add(mnCatalogos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        btnProductos.setSelected(true);
        if (fProductos == null) {
            fProductos = new frmProductos();
            desktopPane.add(fProductos);
            Dimension desktopSize = desktopPane.getSize();
            Dimension FrameSize = fProductos.getSize();
            fProductos.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            fProductos.show();
        }
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoriasActionPerformed
        btnCategorias.setSelected(true);
        if (fCategorias == null) {
            fCategorias = new frmCategorias();
            desktopPane.add(fCategorias);
            Dimension desktopSize = desktopPane.getSize();
            Dimension FrameSize = fCategorias.getSize();
            fCategorias.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            fCategorias.show();
        }
    }//GEN-LAST:event_btnCategoriasActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        btnClientes.setSelected(true);
        if (fClientes == null) {
            fClientes = new frmClientes();
            desktopPane.add(fClientes);
            Dimension desktopSize = desktopPane.getSize();
            Dimension FrameSize = fClientes.getSize();
            fClientes.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            fClientes.show();
        }
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnContactosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContactosActionPerformed
        btnContactos.setSelected(true);
        if (fContactos == null) {
            fContactos = new frmContactos();
            desktopPane.add(fContactos);
            Dimension desktopSize = desktopPane.getSize();
            Dimension FrameSize = fContactos.getSize();
            fContactos.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            fContactos.show();
        }
    }//GEN-LAST:event_btnContactosActionPerformed

    private void btnLocalidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocalidadesActionPerformed
        btnLocalidades.setSelected(true);
        if (fLocalidades == null) {
            fLocalidades = new frmLocalidades();
            desktopPane.add(fLocalidades);
            Dimension desktopSize = desktopPane.getSize();
            Dimension FrameSize = fLocalidades.getSize();
            fLocalidades.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            fLocalidades.show();
        }
    }//GEN-LAST:event_btnLocalidadesActionPerformed

    private void btnMunicipiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMunicipiosActionPerformed
        btnMunicipios.setSelected(true);
        if (fMunicipios == null) {
            fMunicipios = new frmMunicipios();
            desktopPane.add(fMunicipios);
            Dimension desktopSize = desktopPane.getSize();
            Dimension FrameSize = fMunicipios.getSize();
            fMunicipios.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            fMunicipios.show();
        }
    }//GEN-LAST:event_btnMunicipiosActionPerformed

    private void btnEstadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadosActionPerformed
        btnEstados.setSelected(true);
        if (fEstados == null) {
            fEstados = new frmEstados();
            desktopPane.add(fEstados);
            Dimension desktopSize = desktopPane.getSize();
            Dimension FrameSize = fEstados.getSize();
            fEstados.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            fEstados.show();
        }
    }//GEN-LAST:event_btnEstadosActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        btnUsuarios.setSelected(true);
        if (fUsuarios == null) {
            fUsuarios = new frmUsuarios();
            desktopPane.add(fUsuarios);
            Dimension desktopSize = desktopPane.getSize();
            Dimension FrameSize = fUsuarios.getSize();
            fUsuarios.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            fUsuarios.show();
        }
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnSucursalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSucursalesActionPerformed
        btnSucursales.setSelected(true);
        if (fSucursales == null) {
            fSucursales = new frmSucursales();
            desktopPane.add(fSucursales);
            Dimension desktopSize = desktopPane.getSize();
            Dimension FrameSize = fSucursales.getSize();
            fSucursales.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            fSucursales.show();
        }
    }//GEN-LAST:event_btnSucursalesActionPerformed

    private void btnProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedoresActionPerformed
        btnProveedores.setSelected(true);
        if (fProveedores == null) {
            fProveedores = new frmProveedores();
            desktopPane.add(fProveedores);
            Dimension desktopSize = desktopPane.getSize();
            Dimension FrameSize = fProveedores.getSize();
            fProveedores.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            fProveedores.show();
        }
    }//GEN-LAST:event_btnProveedoresActionPerformed

    private void btnProductosProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosProveedoresActionPerformed
        btnProductosProveedores.setSelected(true);
        if (fProuctosProvedores == null) {
            fProuctosProvedores = new frmProductosProveedores();
            desktopPane.add(fProuctosProvedores);
            Dimension desktopSize = desktopPane.getSize();
            Dimension FrameSize = fProuctosProvedores.getSize();
            fProuctosProvedores.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            fProuctosProvedores.show();
        }
    }//GEN-LAST:event_btnProductosProveedoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JCheckBoxMenuItem btnCategorias;
    public static javax.swing.JCheckBoxMenuItem btnClientes;
    public static javax.swing.JCheckBoxMenuItem btnContactos;
    public static javax.swing.JCheckBoxMenuItem btnEstados;
    public static javax.swing.JCheckBoxMenuItem btnLocalidades;
    public static javax.swing.JCheckBoxMenuItem btnMunicipios;
    public static javax.swing.JCheckBoxMenuItem btnProductos;
    public static javax.swing.JCheckBoxMenuItem btnProductosProveedores;
    public static javax.swing.JCheckBoxMenuItem btnProveedores;
    private javax.swing.JCheckBoxMenuItem btnSalir;
    public static javax.swing.JCheckBoxMenuItem btnSucursales;
    public static javax.swing.JCheckBoxMenuItem btnUsuarios;
    public static javax.swing.JDesktopPane desktopPane;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnArchivo;
    public javax.swing.JMenu mnCatalogos;
    // End of variables declaration//GEN-END:variables
}
