/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ViewLayer;

import BussinesModelLayer.Contactos;
import BussinesModelLayer.Localidades;
import BussinesModelLayer.Municipios;
import BussinesModelLayer.Estados;
import java.text.ParseException;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author zerme
 */
public class frmNMContacto extends javax.swing.JDialog {

    private int idContacto = 0;
    private Contactos contacto = new Contactos();
    private Localidades localidad = new Localidades();
    private Municipios municipio = new Municipios();
    private Estados estado = new Estados();
    private LinkedList<Integer> idLocalidad = new LinkedList<>();
    private LinkedList<Integer> idMunicipio = new LinkedList<>();
    private LinkedList<Integer> idEstado = new LinkedList<>();
    /**
     * Creates new form frmNMProducto
     */
    
    public frmNMContacto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public frmNMContacto() {
        initComponents();
        llenarComboBoxEstados();
        setLocationRelativeTo(null);
        municipio.setIdEstado(idEstado.getFirst());
        llenarComboBoxMunicipios();
        localidad.setIdMunicipio(idMunicipio.getFirst());
        llenarComboBoxLocalidades();
    }
    
    //Constructor para modificar
    public frmNMContacto(int idContacto) throws ParseException {
        initComponents();
        setLocationRelativeTo(null);
        
        this.idContacto = idContacto;//Guardar el id mandado
        
        contacto.setIdContacto(idContacto);
        contacto.GetById();//Consulta por id
        
        //Llenado de los campos con la consulta hecha
        txtCodigoPostal.setText(String.valueOf(contacto.getCodigoPostal()));
        txtComuna.setText(contacto.getComuna());
        txtCalle.setText(contacto.getCalle());
        txtTelefono.setText(contacto.getTelefono());
        
        //Llenado del combo box y seleccion
        idEstado.clear();
        comboEstado.removeAllItems();
        llenarComboBoxEstados();
        estado.setIdEstado(contacto.getIdEstado());
        estado.GetById();
        comboEstado.setSelectedItem(estado.getEstado());
        
        municipio.setIdMunicipio(contacto.getIdMunicipio());
        municipio.GetById();
        idMunicipio.clear();
        comboMunicipios.removeAllItems();
        llenarComboBoxMunicipios();
        comboMunicipios.setSelectedItem(municipio.getMunicipio());
        
        localidad.setIdLocalidad(contacto.getIdLocalidad());
        localidad.GetById();
        idLocalidad.clear();
        comboLocalidad.removeAllItems();
        llenarComboBoxLocalidades();
        comboLocalidad.setSelectedItem(localidad.getLocalidad());

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCodigoPostal = new javax.swing.JTextField();
        comboLocalidad = new javax.swing.JComboBox<>();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnAgregarLocalidad = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        txtCalle = new javax.swing.JTextField();
        txtComuna = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        comboMunicipios = new javax.swing.JComboBox<>();
        btnAgregarMunicipio = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        comboEstado = new javax.swing.JComboBox<>();
        btnAgregarEstado = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Codigo Postal:");

        jLabel2.setText("Localidad:");

        jLabel4.setText("Comuna:");

        txtCodigoPostal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoPostalKeyTyped(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnAgregarLocalidad.setText("+");
        btnAgregarLocalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarLocalidadActionPerformed(evt);
            }
        });

        jLabel6.setText("<html><body>  Nueva<br>Localidad</body></html>");

        jLabel7.setText("Calle:");

        jLabel9.setText("Telefono:");

        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });

        jLabel5.setText("Municipio:");

        jLabel8.setText("Estado:");

        comboMunicipios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMunicipiosActionPerformed(evt);
            }
        });

        btnAgregarMunicipio.setText("+");
        btnAgregarMunicipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarMunicipioActionPerformed(evt);
            }
        });

        jLabel10.setText("<html><body>  Nuevo<br>Municipio</body></html>");

        comboEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEstadoActionPerformed(evt);
            }
        });

        btnAgregarEstado.setText("+");
        btnAgregarEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarEstadoActionPerformed(evt);
            }
        });

        jLabel11.setText("<html><body>  Nuevo<br>Estado</body></html>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(btnCancelar)
                .addGap(79, 79, 79)
                .addComponent(btnGuardar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txtCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtComuna, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtCodigoPostal, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(comboLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAgregarLocalidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(comboMunicipios, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAgregarMunicipio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(comboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAgregarEstado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregarEstado)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboMunicipios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregarMunicipio)
                            .addComponent(jLabel5)))
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregarLocalidad)))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigoPostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtComuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnGuardar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.getAccessibleContext().setAccessibleName("<html><body>Nueva<br>Localidad</body></html>");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        if (txtCodigoPostal.getText().isEmpty() || txtCalle.getText().isEmpty() || txtTelefono.getText().isEmpty() || txtComuna.getText().isEmpty() || idLocalidad.isEmpty() || idMunicipio.isEmpty() || idEstado.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Ingresa todos los campos");
        } else {
            
            if (idContacto == 0) {
                if (new Contactos(0, Integer.parseInt(txtCodigoPostal.getText()),
                        txtComuna.getText(),
                        txtCalle.getText(),
                        txtTelefono.getText(),
                        idEstado.get(comboEstado.getSelectedIndex()),
                        idMunicipio.get(comboMunicipios.getSelectedIndex()),
                        idLocalidad.get(comboLocalidad.getSelectedIndex())).Add()) {
                    JOptionPane.showMessageDialog(rootPane, "Contacto agregado correctamente!");
                    this.dispose();
                }
            } else {
                contacto.setCodigoPostal(Integer.parseInt(txtCodigoPostal.getText()));
                contacto.setComuna(txtComuna.getText());
                contacto.setCalle(txtCalle.getText());
                contacto.setTelefono(txtTelefono.getText());
                contacto.setIdEstado(idEstado.get(comboEstado.getSelectedIndex()));
                contacto.setIdMunicipio(idMunicipio.get(comboMunicipios.getSelectedIndex()));
                contacto.setIdLocalidad(idLocalidad.get(comboLocalidad.getSelectedIndex()));
                if (contacto.Update()) {
                    JOptionPane.showMessageDialog(rootPane, "Contacto actualizado correctamente!");
                    this.dispose();
                }

            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        if (txtTelefono.getText().length() > 9) {
            evt.consume();
        } else {
            esNumero(evt, txtTelefono);
        }
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void btnAgregarLocalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarLocalidadActionPerformed
        frmNMLocalidad obj = new frmNMLocalidad();
        obj.setTitle("Nueva Localidad");
        obj.setModal(true);
        obj.setVisible(true);
        localidad.setIdMunicipio(idMunicipio.get(comboMunicipios.getSelectedIndex()));
        idLocalidad.clear();
        comboLocalidad.removeAllItems();
        llenarComboBoxLocalidades();
    }//GEN-LAST:event_btnAgregarLocalidadActionPerformed

    private void txtCodigoPostalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoPostalKeyTyped
        if (txtCodigoPostal.getText().length() > 4) {
            evt.consume();
        } else {
            esNumero(evt, txtCodigoPostal);
        }
    }//GEN-LAST:event_txtCodigoPostalKeyTyped

    private void comboMunicipiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMunicipiosActionPerformed
        if (!idMunicipio.isEmpty()) {
            localidad.setIdMunicipio(idMunicipio.get(comboMunicipios.getSelectedIndex()));
            idLocalidad.clear();
            comboLocalidad.removeAllItems();
            llenarComboBoxLocalidades();
        }
    }//GEN-LAST:event_comboMunicipiosActionPerformed

    private void btnAgregarMunicipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarMunicipioActionPerformed
        frmNMMunicipio obj = new frmNMMunicipio();
        obj.setTitle("Nuevo municipio");
        obj.setModal(true);
        obj.setVisible(true);
        municipio.setIdEstado(idEstado.get(comboEstado.getSelectedIndex()));
        idMunicipio.clear();
        comboMunicipios.removeAllItems();
        llenarComboBoxMunicipios();
    }//GEN-LAST:event_btnAgregarMunicipioActionPerformed

    private void comboEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEstadoActionPerformed
        if (!idEstado.isEmpty()) {
            municipio.setIdEstado(idEstado.get(comboEstado.getSelectedIndex()));
            idMunicipio.clear();
            comboMunicipios.removeAllItems();
            llenarComboBoxMunicipios();
        }
        if (!idMunicipio.isEmpty()) {
            localidad.setIdMunicipio(idMunicipio.get(comboMunicipios.getSelectedIndex()));
            idLocalidad.clear();
            comboLocalidad.removeAllItems();
            llenarComboBoxLocalidades();
        }else{
            idLocalidad.clear();
            comboLocalidad.removeAllItems();
        }
    }//GEN-LAST:event_comboEstadoActionPerformed

    private void btnAgregarEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarEstadoActionPerformed
        frmNMEstado obj = new frmNMEstado();
        obj.setTitle("Nuevo Estado");
        obj.setModal(true);
        obj.setVisible(true);
        idEstado.clear();
        comboEstado.removeAllItems();
        llenarComboBoxEstados();
    }//GEN-LAST:event_btnAgregarEstadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmNMContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmNMContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmNMContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmNMContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmNMContacto dialog = new frmNMContacto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public void llenarComboBoxLocalidades(){
        DefaultTableModel res = localidad.GetAllModelIDMunicipio();
        for (int i = 0; i < res.getRowCount(); i++) {
            comboLocalidad.addItem(String.valueOf(res.getValueAt(i, 1)));
            idLocalidad.add(Integer.parseInt(String.valueOf(res.getValueAt(i, 0))));
        }
    }
    
    public void llenarComboBoxMunicipios(){
        DefaultTableModel res = municipio.GetAllModelIDEstado();
        for (int i = 0; i < res.getRowCount(); i++) {
            comboMunicipios.addItem(String.valueOf(res.getValueAt(i, 1)));
            idMunicipio.add(Integer.parseInt(String.valueOf(res.getValueAt(i, 0))));
        }
    }
    
    public void llenarComboBoxEstados(){
        DefaultTableModel res = estado.GetAllModel();
        for (int i = 0; i < res.getRowCount(); i++) {
            comboEstado.addItem(String.valueOf(res.getValueAt(i, 1)));
            idEstado.add(Integer.parseInt(String.valueOf(res.getValueAt(i, 0))));
        }
    }
    
    public void esNumero (java.awt.event.KeyEvent evt, javax.swing.JTextField txt){
        char caracter = evt.getKeyChar();

        // Verificar si la tecla pulsada no es un digito
        if(((caracter < '0') ||
           (caracter > '9')) &&
           (caracter != '\b' /*corresponde a BACK_SPACE*/))
        {
           evt.consume();  // ignorar el evento de teclado
        }

    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarEstado;
    private javax.swing.JButton btnAgregarLocalidad;
    private javax.swing.JButton btnAgregarMunicipio;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> comboEstado;
    private javax.swing.JComboBox<String> comboLocalidad;
    private javax.swing.JComboBox<String> comboMunicipios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCalle;
    private javax.swing.JTextField txtCodigoPostal;
    private javax.swing.JTextField txtComuna;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
