/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ViewLayer;

import BussinesModelLayer.ProductosProveedores;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.InternalFrameAdapter;
import javax.swing.event.InternalFrameEvent;

/**
 *
 * @author zerme
 */
public class frmProductosProveedores extends javax.swing.JInternalFrame {


    /**
     * Creates new form frmProductos
     */
    public frmProductosProveedores() {
        initComponents();
        tblProductosProveedores.setModel(new ProductosProveedores().GetAllModel());
        new TableDesing().desingOfTable(tblProductosProveedores);
        addInternalFrameListener(new InternalFrameAdapter(){
            public void internalFrameClosing(InternalFrameEvent e) {
                frmMain.fProuctosProvedores = null;
                frmMain.btnProductosProveedores.setSelected(false);
            }
        });
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnActualizar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnOrdenarProducto = new javax.swing.JButton();
        btnBuscarProducto = new javax.swing.JButton();
        btnOrdenarProveedor = new javax.swing.JButton();
        btnBuscarProveedor = new javax.swing.JButton();
        scroll = new javax.swing.JScrollPane();
        tblProductosProveedores = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Productos Proveedores");
        setVisible(true);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btnActualizar.setText("Actualizar");
        btnActualizar.setFocusable(false);
        btnActualizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnActualizar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnActualizar);

        btnNuevo.setText("Nuevo");
        btnNuevo.setFocusable(false);
        btnNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNuevo);

        btnModificar.setText("Modificar");
        btnModificar.setFocusable(false);
        btnModificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnModificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnModificar);

        btnEliminar.setText("Eliminar");
        btnEliminar.setFocusable(false);
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEliminar);

        btnOrdenarProducto.setText("Ordenar Por Producto");
        btnOrdenarProducto.setFocusable(false);
        btnOrdenarProducto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOrdenarProducto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnOrdenarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenarProductoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnOrdenarProducto);

        btnBuscarProducto.setText("Buscar Por Producto");
        btnBuscarProducto.setFocusable(false);
        btnBuscarProducto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuscarProducto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProductoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnBuscarProducto);

        btnOrdenarProveedor.setText("Ordenar Por Proveedor");
        btnOrdenarProveedor.setFocusable(false);
        btnOrdenarProveedor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOrdenarProveedor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnOrdenarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenarProveedorActionPerformed(evt);
            }
        });
        jToolBar1.add(btnOrdenarProveedor);

        btnBuscarProveedor.setText("Buscar Por Proveedor");
        btnBuscarProveedor.setFocusable(false);
        btnBuscarProveedor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuscarProveedor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBuscarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProveedorActionPerformed(evt);
            }
        });
        jToolBar1.add(btnBuscarProveedor);

        tblProductosProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scroll.setViewportView(tblProductosProveedores);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(scroll)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        frmNMProductoProveedor obj = new frmNMProductoProveedor();
        obj.setTitle("Nueva Relacion");
        obj.setModal(true);
        obj.setVisible(true);
        tblProductosProveedores.setModel(new ProductosProveedores().GetAllModel());
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        if (tblProductosProveedores.getSelectedRow()>= 0) {           
            int idProductoProveedor = (int) tblProductosProveedores.getValueAt(tblProductosProveedores.getSelectedRow(), 0);
            
            frmNMProductoProveedor obj;
            try {
                obj = new frmNMProductoProveedor(idProductoProveedor);
                obj.setTitle("Modificar Relacion");
                obj.setModal(true);
                obj.setVisible(true);
            } catch (ParseException ex) {
                Logger.getLogger(frmProductosProveedores.class.getName()).log(Level.SEVERE, null, ex);
            }

            tblProductosProveedores.setModel(new ProductosProveedores().GetAllModel());

        }else{
            JOptionPane.showMessageDialog(rootPane, "Selecciona una relacion");
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        tblProductosProveedores.setModel(new ProductosProveedores().GetAllModel());
        JOptionPane.showMessageDialog(rootPane, "Datos Actualizados");
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (tblProductosProveedores.getSelectedRow()>= 0) {
            int idProductoProveedor = (int) tblProductosProveedores.getValueAt(tblProductosProveedores.getSelectedRow(), 0);
            ProductosProveedores productoproveedor = new ProductosProveedores();
            productoproveedor.setIdProductoproveedor(idProductoProveedor);
            if(productoproveedor.Delete()){
                JOptionPane.showMessageDialog(rootPane, "Relacion eliminada correctamente");
            }else {
                JOptionPane.showMessageDialog(rootPane, "No ha sido posible eliminar la relacion");
            }
            tblProductosProveedores.setModel(productoproveedor.GetAllModel());
        }else{
            JOptionPane.showMessageDialog(rootPane, "Selecciona una relacion");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnOrdenarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarProductoActionPerformed
        tblProductosProveedores.setModel(new ProductosProveedores().GetAllModelOrderProdu());
        JOptionPane.showMessageDialog(rootPane, "Datos Ordenados");
    }//GEN-LAST:event_btnOrdenarProductoActionPerformed

    private void btnBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProductoActionPerformed
        frmSProductoProveedor obj = new frmSProductoProveedor();
        obj.setTitle("Busqueda por nombre");
        obj.setModal(true);
        obj.setVisible(true);
    }//GEN-LAST:event_btnBuscarProductoActionPerformed

    private void btnOrdenarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarProveedorActionPerformed
       tblProductosProveedores.setModel(new ProductosProveedores().GetAllModelOrderProve());
        JOptionPane.showMessageDialog(rootPane, "Datos Ordenados");
    }//GEN-LAST:event_btnOrdenarProveedorActionPerformed

    private void btnBuscarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProveedorActionPerformed
        frmSProveedorProducto obj = new frmSProveedorProducto();
        obj.setTitle("Busqueda por nombre");
        obj.setModal(true);
        obj.setVisible(true);
    }//GEN-LAST:event_btnBuscarProveedorActionPerformed

    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscarProducto;
    private javax.swing.JButton btnBuscarProveedor;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnOrdenarProducto;
    private javax.swing.JButton btnOrdenarProveedor;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JScrollPane scroll;
    public static javax.swing.JTable tblProductosProveedores;
    // End of variables declaration//GEN-END:variables

}
